spring.datasource.url=jdbc:postgresql://localhost:5435/order_db
spring.datasource.username=postgres

spring.kafka.bootstrap-servers=localhost:9093

spring.data.redis.host=localhost
spring.data.redis.port=6380
spring.data.redis.timeout=2000ms